![Modelo](../data/img/the-queens-gambit-netflix%20copia.jpg)

In [ ]:
import pandas as pd
import re

In [ ]:
df = pd.read_csv("../data/raw/chess_games.csv")

df.head()

In [ ]:
df['AN']

In [ ]:
df['AN'].str.contains(r'\[%eval', na=False).value_counts()

# Nos quedaremos solo con las partidas con evaluaciones para entrenar al modelo

In [ ]:
df_eval = pd.read_csv("../data/raw/partidas_SF.csv")

df_eval.info()

In [ ]:
df_eval['Event'].value_counts()

In [ ]:
# Como la columna Event tiene valores mal equilibrados entre partidas de Torneo y amistosas la borro del
# DF porque no me parece que pueda ser representativa, lo mismo con UTCDate y UTCTime.
# Y como hay muchisimas partidas eliminamos los nulos de todas la columnas, y borro lo valores nulos

df_chess= df_eval.drop(['Event','UTCDate','UTCTime'], axis=1).dropna()

df_chess.info()

In [ ]:
df_chess.head()

In [ ]:
print(df_chess['White'].value_counts())

# En principio estas columnas para un modelo predictivo general no nos aportaría nada, con lo que las 
# eliminaré del df principal.
# Podría dejarlas para otro modelo que te dijera estadisticas de determinado jugador, tipo de juego, ELO,
# y otras stats para por ejemplo realizar una predicción contra él.

In [ ]:
cuenta_blancas = df_chess['White'].value_counts()
jugadores_frecuentes_blancas = cuenta_blancas[cuenta_blancas > 50].index

cuenta_negras = df_chess['Black'].value_counts()
jugadores_frecuentes_negras = cuenta_negras[cuenta_negras > 50].index

df_chess = df_chess[
    (df_chess['White'].isin(jugadores_frecuentes_blancas)) &
    (df_chess['Black'].isin(jugadores_frecuentes_negras))
]

In [ ]:
df_chess.info()

In [ ]:
print(df_chess['Result'].value_counts())
# Está bastante equilibrado entre victorias blancas y negras

In [ ]:
# Comprobamos el número de partidas registradas para cada apertura
df_chess['ECO'].value_counts()

In [ ]:
# Como hay mucha fragmentación, y como sé que la letra (A, B, C, D...) representa a un tipo concreto
# de apertura creo una columna nueva solo con el valor del tipo

df_chess['ECO_Family'] = df_chess['ECO'].str[0]
print(df_chess['ECO_Family'].value_counts())
df_chess.drop(['ECO'])

In [ ]:
# Fonction pour extraire les évaluations des coups et les convertir en une liste.

def extraer_evals(un_texte):
    evals = []
    start = 0
    while True:
        st = un_texte.find('[%eval ', start)
        if st == -1:
            break
        end_idx = un_texte.find(']', st)
        if end_idx == -1:
            break
        
        eval_str = un_texte[st + len('[%eval '): end_idx].strip()
        
        if eval_str.startswith('#'):
            if eval_str.startswith('#-'):
                evals.append(-100.0)
            else:
                evals.append(100.0)
        else:
            try:
                evals.append(float(eval_str))
            except ValueError:
                evals.append(None)
        
        start = end_idx + 1
    return evals

# Essaie avec une ligne qui contient des évaluations.
fila_test = df_chess[df_chess['AN'].str.contains('%eval')].iloc[2]  # Prends la première ligne avec des évaluations
print(fila_test['AN'][:500])  # Nous affichons les 500 premiers caractères pour vérifier
print(extraer_evals(fila_test['AN']))

In [ ]:
# 1. Filtra partidas que tienen evaluaciones
df_evals = df_chess[df_chess['AN'].str.contains('%eval', na=False)].copy()

# 2. Extrae todas las evaluaciones de cada partida
df_evals['evals'] = df_evals['AN'].apply(extraer_evals)

# 3. Calcula apertura, medio juego y final
from statistics import mean

def evals_por_fases(evals):
    n = len(evals)
    if n == 0:
        return None, None, None
    tercio = n // 3 or 1
    apertura = mean([e for e in evals[:tercio] if e is not None]) if evals[:tercio] else None
    medio = mean([e for e in evals[tercio:2*tercio] if e is not None]) if evals[tercio:2*tercio] else None
    final = mean([e for e in evals[2*tercio:] if e is not None]) if evals[2*tercio:] else None
    return apertura, medio, final

df_evals[['eval_apertura', 'eval_medio', 'eval_final']] = df_evals['evals'].apply(
    lambda x: pd.Series(evals_por_fases(x))
)

In [ ]:
df_evals= df_evals.drop(['WhiteRatingDiff','BlackRatingDiff', 'Opening'], axis=1)

In [ ]:
df_evals.head()

In [ ]:
df_evals.to_csv("../data/raw/partidas_final.csv", index=False)

In [95]:
df_1 = pd.read_csv('../data/raw/partidas_final.csv')
df_1.head()

,White,Black,Result,WhiteElo,BlackElo,ECO,TimeControl,Termination,AN,ECO_Family,evals,eval_apertura,eval_medio,eval_final
0,t_b,Itseyce,0-1,1569,1496,C01,60+0,Normal,1. e4 { [%eval 0.24] } 1... e6 { [%eval 0.22] ...,C,"[0.24, 0.22, 0.32, 0.15, 0.23, 0.13, 0.06, -0....",-0.094118,-1.076471,-7.000000
1,Itseyce,gustavocesarpelli,1-0,1509,1433,A25,60+0,Normal,1. c4 { [%eval 0.06] } 1... e5 { [%eval 0.04] ...,A,"[0.06, 0.04, -0.03, 0.0, 0.0, -0.2, -0.05, -0....",-0.018000,0.965333,31.627647
2,peapea,dojocleaninh,0-1,1338,1864,C21,60+0,Time forfeit,1. e4 { [%eval 0.25] } 1... e5 { [%eval 0.31] ...,C,"[0.25, 0.31, 0.16, 0.15, 0.01, 0.01, -0.19, -0...",-0.138667,0.334667,-3.406875
3,bound7,accionado,1-0,1534,1599,A00,60+0,Normal,1. g3 { [%eval -0.24] } 1... d5 { [%eval 0.05]...,A,"[-0.24, 0.05, -0.33, -0.03, -0.27, -0.17, -0.2...",0.455909,4.242727,73.102273
4,altuntun,lchuza_otro,0-1,1361,1594,B20,60+0,Normal,1. e4 { [%eval 0.31] } 1... c5 { [%eval 0.37] ...,B,"[0.31, 0.37, -1.0, -1.3, -2.2, -1.34, -1.63, -...",-1.340833,-9.968333,-87.392308

In [96]:
df_1['Result'] = df_1['Result'].map({
    '1-0': 1,
    '1/2-1/2': 0,
    '0-1': -1})

In [97]:
df_1.head(2)

,White,Black,Result,WhiteElo,BlackElo,ECO,TimeControl,Termination,AN,ECO_Family,evals,eval_apertura,eval_medio,eval_final
0,t_b,Itseyce,-1,1569,1496,C01,60+0,Normal,1. e4 { [%eval 0.24] } 1... e6 { [%eval 0.22] ...,C,"[0.24, 0.22, 0.32, 0.15, 0.23, 0.13, 0.06, -0....",-0.094118,-1.076471,-7.000000
1,Itseyce,gustavocesarpelli,1,1509,1433,A25,60+0,Normal,1. c4 { [%eval 0.06] } 1... e5 { [%eval 0.04] ...,A,"[0.06, 0.04, -0.03, 0.0, 0.0, -0.2, -0.05, -0....",-0.018000,0.965333,31.627647

In [99]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21411 entries, 0 to 21410
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   White          21411 non-null  object
 1   Black          21411 non-null  object
 2   Result         21411 non-null  int64
 3   WhiteElo       21411 non-null  int64
 4   BlackElo       21411 non-null  int64
 5   ECO            21411 non-null  object
 6   TimeControl    21411 non-null  object
 7   Termination    21411 non-null  object
 8   AN             21411 non-null  object
 9   ECO_Family     21411 non-null  object
 10  evals          21411 non-null  object
 11  eval_apertura  21411 non-null  float64
 12  eval_medio     21411 non-null  float64
 13  eval_final     21411 non-null  float64
dtypes: float64(3), int64(3), object(8)
memory usage: 2.3+ MB

In [ ]:
def limpiar_anotaciones(an_str):
    return re.sub(r'[!?]+', '', an_str)

df_1['AN'] = df_1['AN'].apply(limpiar_anotaciones)

In [101]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21411 entries, 0 to 21410
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   White          21411 non-null  object
 1   Black          21411 non-null  object
 2   Result         21411 non-null  int64
 3   WhiteElo       21411 non-null  int64
 4   BlackElo       21411 non-null  int64
 5   ECO            21411 non-null  object
 6   TimeControl    21411 non-null  object
 7   Termination    21411 non-null  object
 8   AN             21411 non-null  object
 9   ECO_Family     21411 non-null  object
 10  evals          21411 non-null  object
 11  eval_apertura  21411 non-null  float64
 12  eval_medio     21411 non-null  float64
 13  eval_final     21411 non-null  float64
dtypes: float64(3), int64(3), object(8)
memory usage: 2.3+ MB

In [103]:
chess = df_1.drop(['eval_apertura', 'eval_medio', 'eval_final'], axis=1)

In [104]:
chess.head()

,White,Black,Result,WhiteElo,BlackElo,ECO,TimeControl,Termination,AN,ECO_Family,evals
0,t_b,Itseyce,-1,1569,1496,C01,60+0,Normal,1. e4 { [%eval 0.24] } 1... e6 { [%eval 0.22] ...,C,"[0.24, 0.22, 0.32, 0.15, 0.23, 0.13, 0.06, -0...."
1,Itseyce,gustavocesarpelli,1,1509,1433,A25,60+0,Normal,1. c4 { [%eval 0.06] } 1... e5 { [%eval 0.04] ...,A,"[0.06, 0.04, -0.03, 0.0, 0.0, -0.2, -0.05, -0...."
2,peapea,dojocleaninh,-1,1338,1864,C21,60+0,Time forfeit,1. e4 { [%eval 0.25] } 1... e5 { [%eval 0.31] ...,C,"[0.25, 0.31, 0.16, 0.15, 0.01, 0.01, -0.19, -0..."
3,bound7,accionado,1,1534,1599,A00,60+0,Normal,1. g3 { [%eval -0.24] } 1... d5 { [%eval 0.05]...,A,"[-0.24, 0.05, -0.33, -0.03, -0.27, -0.17, -0.2..."
4,altuntun,lchuza_otro,-1,1361,1594,B20,60+0,Normal,1. e4 { [%eval 0.31] } 1... c5 { [%eval 0.37] ...,B,"[0.31, 0.37, -1.0, -1.3, -2.2, -1.34, -1.63, -..."

In [105]:
chess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21411 entries, 0 to 21410
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   White        21411 non-null  object
 1   Black        21411 non-null  object
 2   Result       21411 non-null  int64
 3   WhiteElo     21411 non-null  int64
 4   BlackElo     21411 non-null  int64
 5   ECO          21411 non-null  object
 6   TimeControl  21411 non-null  object
 7   Termination  21411 non-null  object
 8   AN           21411 non-null  object
 9   ECO_Family   21411 non-null  object
 10  evals        21411 non-null  object
dtypes: int64(3), object(8)
memory usage: 1.8+ MB

In [107]:
chess.to_csv("../data/raw/df_chess.csv", index=False)