In [1]:
import pandas as pd

In [5]:
# Cargamos el dataset en un primer DF

df = pd.read_csv("../data/raw/chess_games.csv")

df.head()

,Event,White,Black,Result,UTCDate,UTCTime,WhiteElo,BlackElo,WhiteRatingDiff,BlackRatingDiff,ECO,Opening,TimeControl,Termination,AN
0,Classical,eisaaaa,HAMID449,1-0,2016.06.30,22:00:01,1901,1896,11.0,-11.0,D10,Slav Defense,300+5,Time forfeit,1. d4 d5 2. c4 c6 3. e3 a6 4. Nf3 e5 5. cxd5 e...
1,Blitz,go4jas,Sergei1973,0-1,2016.06.30,22:00:01,1641,1627,-11.0,12.0,C20,King's Pawn Opening: 2.b3,300+0,Normal,1. e4 e5 2. b3 Nf6 3. Bb2 Nc6 4. Nf3 d6 5. d3 ...
2,Blitz tournament,Evangelistaizac,kafune,1-0,2016.06.30,22:00:02,1647,1688,13.0,-13.0,B01,Scandinavian Defense: Mieses-Kotroc Variation,180+0,Time forfeit,1. e4 d5 2. exd5 Qxd5 3. Nf3 Bg4 4. Be2 Nf6 5....
3,Correspondence,Jvayne,Wsjvayne,1-0,2016.06.30,22:00:02,1706,1317,27.0,-25.0,A00,Van't Kruijs Opening,-,Normal,1. e3 Nf6 2. Bc4 d6 3. e4 e6 4. Nf3 Nxe4 5. Nd...
4,Blitz tournament,kyoday,BrettDale,0-1,2016.06.30,22:00:02,1945,1900,-14.0,13.0,B90,"Sicilian Defense: Najdorf, Lipnitsky Attack",180+0,Time forfeit,1. e4 c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. N...

In [7]:
df['AN']

0          1. d4 d5 2. c4 c6 3. e3 a6 4. Nf3 e5 5. cxd5 e...
1          1. e4 e5 2. b3 Nf6 3. Bb2 Nc6 4. Nf3 d6 5. d3 ...
2          1. e4 d5 2. exd5 Qxd5 3. Nf3 Bg4 4. Be2 Nf6 5....
3          1. e3 Nf6 2. Bc4 d6 3. e4 e6 4. Nf3 Nxe4 5. Nd...
4          1. e4 c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. N...
                                 ...
6256179    1. e4 c5 2. Nf3 d6 3. d4 Qa5+ 4. Bd2 Qc7 5. Bc...
6256180    1. e4 e5 2. Nf3 h6 3. Nc3 d6 4. Bc4 Qf6 5. Nd5...
6256181    1. e4 { [%eval 0.22] } 1... c5 { [%eval 0.35] ...
6256182    1. Nf3 d5 2. c4 dxc4 3. Qa4+ c6 4. Qxc4 Nf6 5....
6256183    1. e4 e6 2. d4 d6 3. Nc3 c6 4. Nf3 Be7 5. Bc4 ...
Name: AN, Length: 6256184, dtype: object

In [ ]:
df['AN'].str.contains(r'\[%eval', na=False).value_counts()

# Nos quedaremos solo con las partidas con evaluaciones para entrenar al modelo

AN
False    5455688
True      800496
Name: count, dtype: int64

In [4]:
# Quedarse solo con partidas con evaluaciones de Stockfish
df_con_eval = df[df['AN'].str.contains(r'\[%eval', na=False)]

# Lo guardamos para en sucesivas cargas no tener que hacer todo el proceso anterior.
df_con_eval.to_csv("../data/raw/partidas_SF.csv", index=False)
df_eval = pd.read_csv("../data/raw/partidas_SF.csv")

df_eval.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800496 entries, 0 to 800495
Data columns (total 15 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Event            800496 non-null  object
 1   White            800496 non-null  object
 2   Black            800496 non-null  object
 3   Result           800496 non-null  object
 4   UTCDate          800496 non-null  object
 5   UTCTime          800496 non-null  object
 6   WhiteElo         800496 non-null  int64
 7   BlackElo         800496 non-null  int64
 8   WhiteRatingDiff  799339 non-null  float64
 9   BlackRatingDiff  799339 non-null  float64
 10  ECO              800496 non-null  object
 11  Opening          800496 non-null  object
 12  TimeControl      800496 non-null  object
 13  Termination      800496 non-null  object
 14  AN               800496 non-null  object
dtypes: float64(2), int64(2), object(11)
memory usage: 91.6+ MB

In [6]:
df_eval['Event'].value_counts()

Event
 Classical                224518
 Blitz                    218213
 Bullet                   185885
 Bullet tournament         93777
 Blitz tournament          48977
 Classical tournament      25706
 Correspondence             3412
Classical                      3
Bullet                         2
Blitz                          1
Classical tournament           1
Bullet tournament              1
Name: count, dtype: int64

In [ ]:
# Como la columna Event tiene valores mal equilibrados entre partidas de Torneo y amistosas la borro del
# DF porque no me parece que pueda ser representativa, lo mismo con UTCDate y UTCTime.
# Y como hay muchisimas partidas eliminamos los nulos de todas la columnas, y borro lo valores nulos

df_chess= df_eval.drop(['Event','UTCDate','UTCTime'], axis=1).dropna()

df_chess.info()

<class 'pandas.core.frame.DataFrame'>
Index: 799339 entries, 0 to 800495
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   White            799339 non-null  object
 1   Black            799339 non-null  object
 2   Result           799339 non-null  object
 3   WhiteElo         799339 non-null  int64
 4   BlackElo         799339 non-null  int64
 5   WhiteRatingDiff  799339 non-null  float64
 6   BlackRatingDiff  799339 non-null  float64
 7   ECO              799339 non-null  object
 8   Opening          799339 non-null  object
 9   TimeControl      799339 non-null  object
 10  Termination      799339 non-null  object
 11  AN               799339 non-null  object
dtypes: float64(2), int64(2), object(8)
memory usage: 79.3+ MB

In [20]:
df_chess.head()

,White,Black,Result,WhiteElo,BlackElo,WhiteRatingDiff,BlackRatingDiff,ECO,Opening,TimeControl,Termination,AN
0,chm00002,jan666,1-0,1761,1754,12.0,-12.0,C30,"King's Gambit Declined, Queen's Knight Defense",180+0,Time forfeit,1. e4 { [%eval 0.27] } 1... e5 { [%eval 0.27] ...
1,Damianlamy,BaderBombs,1-0,2134,2128,12.0,-11.0,B21,"Sicilian Defense: Smith-Morra Gambit Accepted,...",300+0,Normal,1. e4 { [%eval 0.31] } 1... c5 { [%eval 0.37] ...
2,jjj333,aldoelapache,1-0,1964,1970,11.0,-12.0,B00,Owen Defense,60+0,Time forfeit,1. e4 { [%eval 0.27] } 1... b6 { [%eval 0.51] ...
3,otger,gmvladimir,0-1,1515,1540,-11.0,10.0,C42,Petrov's Defense,300+0,Normal,1. e4 { [%eval 0.22] } 1... e5 { [%eval 0.25] ...
4,b0nker2,erdema,1-0,1422,1403,11.0,-10.0,D00,Queen's Pawn Game: Mason Attack,300+0,Normal,1. d4 { [%eval 0.24] } 1... d5 { [%eval 0.14] ...

In [ ]:
print(df_chess['White'].value_counts())

# En principio estas columnas para un modelo predictivo general no nos aportaría nada, con lo que las 
# eliminaré del df principal.
# Podría dejarlas para otro modelo que te dijera estadisticas de determinado jugador, tipo de juego, ELO,
# y otras stats para por ejemplo realizar una predicción contra él.

White
pavelpavel              867
Evenflow                799
zafarynl                583
potsy722                573
palang1359              558
                       ...
Zwickzwackzwieback        1
lakefront75               1
silvificknigthchess9      1
karka                     1
KarjalanSotilas           1
Name: count, Length: 85400, dtype: int64

In [18]:
# Comprobamos el número de partidas registradas para cada apertura
df_chess['ECO'].value_counts()

ECO
A00    50014
B01    34749
C00    34335
A40    33932
D00    27165
       ...
C76        1
E03        1
B69        1
E55        1
A93        1
Name: count, Length: 489, dtype: int64

In [ ]:
# Como hay mucha fragmentación, y como sé que la letra (A, B, C, D...) representa a un tipo concreto
# de apertura creo una columna nueva solo con el valor del tipo

df_chess['ECO_Family'] = df_chess['ECO'].str[0]
print(df_chess['ECO_Family'].value_counts())

ECO_Family
C    239888
B    231409
A    200658
D    108236
E     20305
Name: count, dtype: int64

In [28]:
def extraer_evals_sin_re_y_convertir(an_text):
    evals = []
    start = 0
    while True:
        start_idx = an_text.find('[%eval ', start)
        if start_idx == -1:
            break
        end_idx = an_text.find(']', start_idx)
        if end_idx == -1:
            break
        
        eval_str = an_text[start_idx + len('[%eval '): end_idx].strip()
        
        if eval_str.startswith('#'):
            if eval_str.startswith('#-'):
                evals.append(-100.0)
            else:
                evals.append(100.0)
        else:
            try:
                evals.append(float(eval_str))
            except ValueError:
                evals.append(None)
        
        start = end_idx + 1
    return evals

# Probar con una fila que tiene evaluaciones
fila_test = df[df['AN'].str.contains('%eval')].iloc[2]  # Coge la primera fila con evals
print(fila_test['AN'][:500])  # Mostramos los primeros 500 caracteres para revisar
print(extraer_evals_sin_re_y_convertir(fila_test['AN']))

1. e4 { [%eval 0.27] } 1... b6 { [%eval 0.51] } 2. Nf3 { [%eval 0.34] } 2... Bb7 { [%eval 0.41] } 3. e5 { [%eval 0.37] } 3... d6 { [%eval 0.36] } 4. d4 { [%eval 0.27] } 4... dxe5 { [%eval 0.5] } 5. Nxe5 { [%eval 0.41] } 5... Nd7?! { [%eval 1.1] } 6. Bf4?! { [%eval 0.23] } 6... Nxe5 { [%eval 0.19] } 7. Bxe5 { [%eval 0.24] } 7... f6 { [%eval 0.33] } 8. Bg3 { [%eval 0.12] } 8... e6 { [%eval 0.17] } 9. c3 { [%eval 0.02] } 9... Ne7 { [%eval 0.0] } 10. Nd2 { [%eval -0.03] } 10... Nf5 { [%eval 0.24] }
[0.27, 0.51, 0.34, 0.41, 0.37, 0.36, 0.27, 0.5, 0.41, 1.1, 0.23, 0.19, 0.24, 0.33, 0.12, 0.17, 0.02, 0.0, -0.03, 0.24, 0.17, 0.38, 0.34, 0.81, 0.67, 0.98, 0.96, 0.87, 0.62, 1.23, 0.55, 0.58, 0.56, 0.49, 0.22, 0.15, -0.5, 1.96, -0.78, -0.75, -3.25]

In [29]:
# 1. Filtra partidas que tienen evaluaciones
df_evals = df_chess[df_chess['AN'].str.contains('%eval', na=False)].copy()

# 2. Extrae todas las evaluaciones de cada partida
df_evals['evals'] = df_evals['AN'].apply(extraer_evals_sin_re_y_convertir)

# 3. Calcula apertura, medio juego y final
from statistics import mean

def evals_por_fases(evals):
    n = len(evals)
    if n == 0:
        return None, None, None
    tercio = n // 3 or 1
    apertura = mean([e for e in evals[:tercio] if e is not None]) if evals[:tercio] else None
    medio = mean([e for e in evals[tercio:2*tercio] if e is not None]) if evals[tercio:2*tercio] else None
    final = mean([e for e in evals[2*tercio:] if e is not None]) if evals[2*tercio:] else None
    return apertura, medio, final

df_evals[['eval_apertura', 'eval_medio', 'eval_final']] = df_evals['evals'].apply(
    lambda x: pd.Series(evals_por_fases(x))
)

In [31]:
df_evals

,White,Black,Result,WhiteElo,BlackElo,WhiteRatingDiff,BlackRatingDiff,ECO,Opening,TimeControl,Termination,AN,evals,eval_apertura,eval_medio,eval_final
0,chm00002,jan666,1-0,1761,1754,12.0,-12.0,C30,"King's Gambit Declined, Queen's Knight Defense",180+0,Time forfeit,1. e4 { [%eval 0.27] } 1... e5 { [%eval 0.27] ...,"[0.27, 0.27, -0.26, 0.34, -4.91, 0.59, 0.03, 0...",-0.244500,-0.218000,24.101905
1,Damianlamy,BaderBombs,1-0,2134,2128,12.0,-11.0,B21,"Sicilian Defense: Smith-Morra Gambit Accepted,...",300+0,Normal,1. e4 { [%eval 0.31] } 1... c5 { [%eval 0.37] ...,"[0.31, 0.37, 0.24, 0.34, 0.17, 0.14, -0.17, 0....",-0.230541,-0.410811,7.581892
2,jjj333,aldoelapache,1-0,1964,1970,11.0,-12.0,B00,Owen Defense,60+0,Time forfeit,1. e4 { [%eval 0.27] } 1... b6 { [%eval 0.51] ...,"[0.27, 0.51, 0.34, 0.41, 0.37, 0.36, 0.27, 0.5...",0.400000,0.323077,0.194000
3,otger,gmvladimir,0-1,1515,1540,-11.0,10.0,C42,Petrov's Defense,300+0,Normal,1. e4 { [%eval 0.22] } 1... e5 { [%eval 0.25] ...,"[0.22, 0.25, 0.27, 0.34, -0.37, 0.03, 0.04, 0....",0.232353,0.237059,-22.475000
4,b0nker2,erdema,1-0,1422,1403,11.0,-10.0,D00,Queen's Pawn Game: Mason Attack,300+0,Normal,1. d4 { [%eval 0.24] } 1... d5 { [%eval 0.14] ...,"[0.24, 0.14, 0.17, 0.62, 0.48, 1.02, 1.2, 2.5,...",0.992500,1.571500,18.532000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800491,verdu,Roister0,0-1,1794,1814,-10.0,10.0,C00,French Defense: Knight Variation,900+0,Normal,1. e4 { [%eval 0.15] } 1... e6 { [%eval 0.23] ...,"[0.15, 0.23, 0.16, 0.11, 0.07, 0.11, 0.17, 0.0...",-0.167368,-4.030000,-4.625750
800492,Ascarsiul,tsogtb,1-0,1583,1387,5.0,-5.0,C40,King's Pawn Game: Busch-Gass Gambit,720+0,Normal,1. e4 { [%eval 0.19] } 1... e5 { [%eval 0.26] ...,"[0.19, 0.26, 0.29, 1.13, 0.97, 1.29, 1.3, 1.34...",1.023684,1.767895,6.323500
800493,jhonyvidal,JosepPalautordera,1-0,1141,1032,39.0,-31.0,A00,Mieses Opening: Reversed Rat,120+0,Time forfeit,1. d3 { [%eval -0.03] } 1... e5 { [%eval 0.07]...,"[-0.03, 0.07, -0.1, -0.15, -0.43, -0.06, -0.15...",-0.645000,-5.367083,-5.135200
800494,ogor32,HardWoodPusher,1-0,1802,1965,16.0,-16.0,A00,Hungarian Opening: Reversed Modern Defense,0+1,Time forfeit,1. g3 { [%eval -0.25] } 1... d5 { [%eval 0.0] ...,"[-0.25, 0.0, -0.3, 0.03, -0.14, 0.14, -0.04, 2...",-0.003125,-1.309375,-0.340000
800495,matematico1234567890,cecile_creteil,0-1,1660,1658,-11.0,11.0,B21,Sicilian Defense: Smith-Morra Gambit,120+0,Normal,1. e4 { [%eval 0.22] } 1... c5 { [%eval 0.35] ...,"[0.22, 0.35, 0.12, 0.1, 0.07, 0.37, 0.42, 1.18...",0.183125,-0.218750,-2.620556

In [32]:
df_evals.to_csv("partidas_final.csv", index=False)

In [33]:
df_evals['delta_apertura_medio'] = df_evals['eval_medio'] - df_evals['eval_apertura']
df_evals['delta_medio_final'] = df_evals['eval_final'] - df_evals['eval_medio']
df_evals['delta_apertura_final'] = df_evals['eval_final'] - df_evals['eval_apertura']

In [34]:
df_evals

,White,Black,Result,WhiteElo,BlackElo,WhiteRatingDiff,BlackRatingDiff,ECO,Opening,TimeControl,Termination,AN,evals,eval_apertura,eval_medio,eval_final,delta_apertura_medio,delta_medio_final,delta_apertura_final
0,chm00002,jan666,1-0,1761,1754,12.0,-12.0,C30,"King's Gambit Declined, Queen's Knight Defense",180+0,Time forfeit,1. e4 { [%eval 0.27] } 1... e5 { [%eval 0.27] ...,"[0.27, 0.27, -0.26, 0.34, -4.91, 0.59, 0.03, 0...",-0.244500,-0.218000,24.101905,0.026500,24.319905,24.346405
1,Damianlamy,BaderBombs,1-0,2134,2128,12.0,-11.0,B21,"Sicilian Defense: Smith-Morra Gambit Accepted,...",300+0,Normal,1. e4 { [%eval 0.31] } 1... c5 { [%eval 0.37] ...,"[0.31, 0.37, 0.24, 0.34, 0.17, 0.14, -0.17, 0....",-0.230541,-0.410811,7.581892,-0.180270,7.992703,7.812432
2,jjj333,aldoelapache,1-0,1964,1970,11.0,-12.0,B00,Owen Defense,60+0,Time forfeit,1. e4 { [%eval 0.27] } 1... b6 { [%eval 0.51] ...,"[0.27, 0.51, 0.34, 0.41, 0.37, 0.36, 0.27, 0.5...",0.400000,0.323077,0.194000,-0.076923,-0.129077,-0.206000
3,otger,gmvladimir,0-1,1515,1540,-11.0,10.0,C42,Petrov's Defense,300+0,Normal,1. e4 { [%eval 0.22] } 1... e5 { [%eval 0.25] ...,"[0.22, 0.25, 0.27, 0.34, -0.37, 0.03, 0.04, 0....",0.232353,0.237059,-22.475000,0.004706,-22.712059,-22.707353
4,b0nker2,erdema,1-0,1422,1403,11.0,-10.0,D00,Queen's Pawn Game: Mason Attack,300+0,Normal,1. d4 { [%eval 0.24] } 1... d5 { [%eval 0.14] ...,"[0.24, 0.14, 0.17, 0.62, 0.48, 1.02, 1.2, 2.5,...",0.992500,1.571500,18.532000,0.579000,16.960500,17.539500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800491,verdu,Roister0,0-1,1794,1814,-10.0,10.0,C00,French Defense: Knight Variation,900+0,Normal,1. e4 { [%eval 0.15] } 1... e6 { [%eval 0.23] ...,"[0.15, 0.23, 0.16, 0.11, 0.07, 0.11, 0.17, 0.0...",-0.167368,-4.030000,-4.625750,-3.862632,-0.595750,-4.458382
800492,Ascarsiul,tsogtb,1-0,1583,1387,5.0,-5.0,C40,King's Pawn Game: Busch-Gass Gambit,720+0,Normal,1. e4 { [%eval 0.19] } 1... e5 { [%eval 0.26] ...,"[0.19, 0.26, 0.29, 1.13, 0.97, 1.29, 1.3, 1.34...",1.023684,1.767895,6.323500,0.744211,4.555605,5.299816
800493,jhonyvidal,JosepPalautordera,1-0,1141,1032,39.0,-31.0,A00,Mieses Opening: Reversed Rat,120+0,Time forfeit,1. d3 { [%eval -0.03] } 1... e5 { [%eval 0.07]...,"[-0.03, 0.07, -0.1, -0.15, -0.43, -0.06, -0.15...",-0.645000,-5.367083,-5.135200,-4.722083,0.231883,-4.490200
800494,ogor32,HardWoodPusher,1-0,1802,1965,16.0,-16.0,A00,Hungarian Opening: Reversed Modern Defense,0+1,Time forfeit,1. g3 { [%eval -0.25] } 1... d5 { [%eval 0.0] ...,"[-0.25, 0.0, -0.3, 0.03, -0.14, 0.14, -0.04, 2...",-0.003125,-1.309375,-0.340000,-1.306250,0.969375,-0.336875
800495,matematico1234567890,cecile_creteil,0-1,1660,1658,-11.0,11.0,B21,Sicilian Defense: Smith-Morra Gambit,120+0,Normal,1. e4 { [%eval 0.22] } 1... c5 { [%eval 0.35] ...,"[0.22, 0.35, 0.12, 0.1, 0.07, 0.37, 0.42, 1.18...",0.183125,-0.218750,-2.620556,-0.401875,-2.401806,-2.803681