In [ ]:
import chess.pgn
import pandas as pd

# Función para leer el PGN y crear el DataFrame
def process_pgn(pgn_file):
    # Cargar el archivo PGN
    pgn = open(pgn_file)
    
    # Lista para almacenar los resultados de las partidas
    data = []

    # Leer todas las partidas del archivo PGN
    while True:
        try:
            game = chess.pgn.read_game(pgn)
            if game is None:
                break

            # Extraer información del encabezado del PGN
            event = game.headers.get("Event", "?")
            white_player = game.headers.get("White", "?")
            black_player = game.headers.get("Black", "?")
            result = game.headers.get("Result", "?")
            utc_date = game.headers.get("UTCDate", "?")
            utc_time = game.headers.get("UTCTime", "?")
            white_elo = game.headers.get("WhiteElo", "?")
            black_elo = game.headers.get("BlackElo", "?")
            white_rating_diff = game.headers.get("WhiteRatingDiff", "?")
            black_rating_diff = game.headers.get("BlackRatingDiff", "?")
            eco = game.headers.get("ECO", "?")
            opening = game.headers.get("Opening", "?")
            time_control = game.headers.get("TimeControl", "?")
            termination = game.headers.get("Termination", "?")

            # Añadir los datos a la lista
            data.append([event, white_player, black_player, result, utc_date, utc_time,
                         white_elo, black_elo, white_rating_diff, black_rating_diff, eco, 
                         opening, time_control, termination])

        except Exception as e:
            print(f"Error al leer una partida: {e}")
            break
    
    # Crear el DataFrame con la información
    df = pd.DataFrame(data, columns=[
        "Event", "White", "Black", "Result", "UTCDate", "UTCTime", "WhiteElo", "BlackElo",
        "WhiteRatingDiff", "BlackRatingDiff", "ECO", "Opening", "TimeControl", "Termination"
    ])
    
    return df

# Llamar a la función con el archivo PGN y guardar el DataFrame
df_result = process_pgn("predict.pgn")

# Guardar el DataFrame en un archivo CSV
df_result.to_csv("evaluaciones_partida.csv", index=False)

# Mostrar el DataFrame
df_result

,Event,White,Black,Result,UTCDate,UTCTime,WhiteElo,BlackElo,WhiteRatingDiff,BlackRatingDiff,ECO,Opening,TimeControl,Termination
0,?,Eduardo,Clase,*,?,?,1400,?,?,?,C44,Scotch,40/9000:40/9000:40/9000,unterminated

In [38]:
# Leer el archivo PGN desde la línea 18 hasta el final
def extraer_movimientos_desde_pgn(pgn_path):
    with open(pgn_path, 'r') as file:
        lines = file.readlines()
        # Extraer el texto desde la línea 18 (índice 17 en cero-indexado)
        movimientos = "".join(lines[17:]).strip()
    return movimientos

# Suponiendo que tienes la ruta del archivo PGN
pgn_file_path = 'predict.pgn'

# Extraer el bloque de texto con los movimientos
movimientos_extraidos = extraer_movimientos_desde_pgn(pgn_file_path)

# Añadir este texto como una nueva columna 'AN' en df1
df_result['AN'] = [movimientos_extraidos for _ in range(len(df_result))]

# Mostrar el DataFrame actualizado
df_result

,Event,White,Black,Result,UTCDate,UTCTime,WhiteElo,BlackElo,WhiteRatingDiff,BlackRatingDiff,ECO,Opening,TimeControl,Termination,eval,AN
0,?,Eduardo,Clase,*,?,?,1400,?,?,?,C44,Scotch,40/9000:40/9000:40/9000,unterminated,"[0.06, -0.04, 0.12, -0.12, 0.12, -0.02, 0.69, ...",1. e4 {(e7-e5) +0.04/1 1} e5 {(Ng1-f3 Nb8-c6) ...

In [39]:
df_result['AN'][0]

'1. e4 {(e7-e5) +0.04/1 1} e5 {(Ng1-f3 Nb8-c6) -0.12/1 1} 2. Nf3 {(Nb8-c6\nBf1-b5) +0.12/1 1} Nc6 {(Bf1-b5 Ng8-f6) -0.12/1 1} 3. d4 {(e5xd4 Nf3xd4\nNg8-f6) +0.02/1 1} d6 {(Bf1-b5 e5xd4 Nf3xd4) -0.69/1 1} 4. d5 {(Nc6-e7)\n+0.60/1 1} f6 {(d5xc6 b7xc6) -4.55/1 1} 5. dxc6 {(b7xc6 Bf1-e2) +4.56/1 1}\nbxc6 {(Bf1-e2 Bf8-e7) -5.15/1 1} 6. Ng5 {(f6xg5) -0.02/1 1} f5 {(Bf1-c4)\n-4.30/1 1} 7. Qh5+ {(g7-g6 Qh5-f3) +2.88/1 1} Ke7 {(Qh5-f7+) -M1/1 1} 8.\nQf7# *'

In [40]:
def limpiar_anotaciones(an_str):
    return re.sub(r'[!?]+', '', an_str)

df_result['AN'] = df_result['AN'].apply(limpiar_anotaciones)

In [41]:
df_result

,Event,White,Black,Result,UTCDate,UTCTime,WhiteElo,BlackElo,WhiteRatingDiff,BlackRatingDiff,ECO,Opening,TimeControl,Termination,eval,AN
0,?,Eduardo,Clase,*,?,?,1400,?,?,?,C44,Scotch,40/9000:40/9000:40/9000,unterminated,"[0.06, -0.04, 0.12, -0.12, 0.12, -0.02, 0.69, ...",1. e4 {(e7-e5) +0.04/1 1} e5 {(Ng1-f3 Nb8-c6) ...

In [29]:
import re

log_file_path = '../Analisis2.log'
with open(log_file_path, 'r') as file:
    log_content = file.read()

eval_values = re.findall(r'[\+\-]?\d+[,\.]\d{2}', log_content)

eval_values = [float(value.replace(',', '.')) for value in eval_values]

print(eval_values)

[0.06, -0.04, 0.12, -0.12, 0.12, -0.02, 0.69, -0.6, 4.55, -4.56, 5.15, 0.02, 4.3, -2.88]

In [30]:
import pandas as pd

df_evals = pd.DataFrame({'eval': [eval_values]})

# Mostrar el DataFrame
df_evals.head()

                                                eval
0  [0.06, -0.04, 0.12, -0.12, 0.12, -0.02, 0.69, ...

In [32]:
import pandas as pd

# Asumiendo que ya tienes df1 y df2 definidos:

# Asegúrate de que df2 tiene la misma cantidad de filas que df1
df_result['eval'] = df_evals['eval'].values

df_result

,Event,White,Black,Result,UTCDate,UTCTime,WhiteElo,BlackElo,WhiteRatingDiff,BlackRatingDiff,ECO,Opening,TimeControl,Termination,eval
0,?,Eduardo,Clase,*,?,?,1400,?,?,?,C44,Scotch,40/9000:40/9000:40/9000,unterminated,"[0.06, -0.04, 0.12, -0.12, 0.12, -0.02, 0.69, ..."